const { fetchTranscript } = require('youtube-transcript-plus');
const fs = require('fs');
const path = require('path');

/**
 * Extract video ID from YouTube URL
 * @param {string} url - YouTube URL
 * @returns {string|null} - Video ID or null if invalid
 */
function extractVideoId(url) {
  const patterns = [
    /(?:youtube\.com\/watch\?v=|youtu\.be\/)([^&\n?#]+)/,
    /youtube\.com\/embed\/([^&\n?#]+)/,
    /youtube\.com\/v\/([^&\n?#]+)/
  ];

  for (const pattern of patterns) {
    const match = url.match(pattern);
    if (match && match[1]) {
      return match[1];
    }
  }

  return null;
}

/**
 * Try to fetch transcript with fallback strategy
 * @param {string} videoId - YouTube video ID
 * @returns {Promise<{transcript: Array, type: string}>}
 */
async function fetchTranscriptWithFallback(videoId) {
  // Strategy 1: Try to get English subtitles (manual or auto-generated)
  try {
    console.log('🔍 Fetching English subtitles...');
    const transcript = await fetchTranscript(videoId, {
      lang: 'en'
    });

    if (transcript && transcript.length > 0) {
      // Check if it's auto-generated (this is a heuristic)
      const hasAutoGeneratedMarkers = transcript.some(entry =>
        entry.text.includes('[') || entry.text.includes('♪')
      );

      return {
        transcript,
        type: hasAutoGeneratedMarkers ? 'likely auto-generated' : 'available'
      };
    }
  } catch (error) {
    console.log('⚠️  English subtitles not found, trying default...');
  }

  // Strategy 2: Try without language specification (gets default available)
  try {
    console.log('🔍 Trying default subtitles...');
    const transcript = await fetchTranscript(videoId);

    if (transcript && transcript.length > 0) {
      return { transcript, type: 'default' };
    }
  } catch (error) {
    // All strategies failed
  }

  throw new Error('No subtitles available for this video');
}

/**
 * Download YouTube subtitle and save to file
 * @param {string} url - YouTube URL
 */
async function downloadSubtitle(url) {
  try {
    // Extract video ID
    const videoId = extractVideoId(url);
    if (!videoId) {
      console.error('❌ Invalid YouTube URL');
      console.log('Please provide a valid YouTube URL, for example:');
      console.log('  - https://www.youtube.com/watch?v=VIDEO_ID');
      console.log('  - https://youtu.be/VIDEO_ID');
      process.exit(1);
    }

    console.log(`📹 Video ID: ${videoId}`);
    console.log('⏳ Fetching subtitle...');

    // Fetch transcript with fallback strategy
    const { transcript, type } = await fetchTranscriptWithFallback(videoId);

    // Display subtitle type
    if (type === 'likely auto-generated') {
      console.log('🤖 Using subtitles (likely auto-generated)');
    } else if (type === 'available') {
      console.log('✨ Using available English subtitles');
    } else {
      console.log('📝 Using default available subtitles');
    }

    // Convert transcript to plain text
    const plainText = transcript.map(entry => entry.text).join(' ');

    // Create subtitles directory if it doesn't exist
    const subtitlesDir = path.join(__dirname, 'subtitles');
    if (!fs.existsSync(subtitlesDir)) {
      fs.mkdirSync(subtitlesDir, { recursive: true });
      console.log('📁 Created subtitles directory');
    }

    // Save to file
    const outputPath = path.join(subtitlesDir, `yt_${videoId}.txt`);
    fs.writeFileSync(outputPath, plainText, 'utf-8');

    console.log('✅ Subtitle downloaded successfully!');
    console.log(`📄 Saved to: ${outputPath}`);
    console.log(`📊 Character count: ${plainText.length}`);
    console.log(`📝 Word count: ${plainText.split(/\s+/).length}`);

  } catch (error) {
    if (error.message.includes('No subtitles available')) {
      console.error('❌ Error: No subtitles found for this video');
      console.log('Possible reasons:');
      console.log('  - Video has no subtitles/captions');
      console.log('  - Video is private or deleted');
      console.log('  - Subtitles are disabled');
    } else if (error.message.includes('Could not get transcript')) {
      console.error('❌ Error: Could not get transcript');
      console.log('The video might be private, deleted, or have disabled captions');
    } else if (error.message.includes('Transcript is disabled')) {
      console.error('❌ Error: Subtitles are disabled for this video');
    } else {
      console.error('❌ Error:', error.message);
    }
    process.exit(1);
  }
}

// Main execution
const readline = require('readline');

const args = process.argv.slice(2);

if (args.length === 0) {
  // Interactive mode
  const rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout
  });

  console.log('🎬 YouTube Subtitle Downloader');
  console.log('━'.repeat(50));

  rl.question('Please enter YouTube URL or Video ID: ', (input) => {
    rl.close();

    if (!input || input.trim() === '') {
      console.error('❌ No URL provided');
      process.exit(1);
    }

    const url = input.trim();
    downloadSubtitle(url);
  });
} else {
  // Command line argument mode
  const url = args[0];
  downloadSubtitle(url);
}
