const CARDS = [
  {
    word: "stunning",
    definition: "Extremely impressive or attractive; causing astonishment or admiration",
    example: "The view from the mountain top was absolutely stunning.",
    synonyms: "breathtaking, spectacular, remarkable, dazzling",
    notes: "",
  },
  {
    word: "trim",
    definition: "To make neat or tidy by cutting away irregular or unwanted parts; to reduce in size",
    example: "She decided to trim her hair before the wedding.",
    synonyms: "cut, clip, prune, pare",
    notes: "",
  },
  {
    word: "asthenosphere",
    definition:
      "The upper layer of the earth's mantle, below the lithosphere, in which there is relatively low resistance to plastic flow",
    example: "The asthenosphere allows tectonic plates to move across the Earth's surface.",
    synonyms: "",
    notes: "地質學術語：軟流圈",
  },
  {
    word: "crumpled",
    definition: "Crushed or pressed into irregular folds or wrinkles",
    example: "He found a crumpled piece of paper in his pocket.",
    synonyms: "wrinkled, creased, rumpled, crushed",
    notes: "",
  },
  {
    word: "uplifted",
    definition: "Raised to a higher position or level; elevated physically or emotionally",
    example: "The mountain range was uplifted by tectonic forces millions of years ago.",
    synonyms: "elevated, raised, lifted, hoisted",
    notes: "Note: 原文為 'uplisted' 可能是拼寫錯誤",
  },
  {
    word: "trench",
    definition: "A long, narrow ditch or depression in the ground",
    example: "The Mariana Trench is the deepest part of the world's oceans.",
    synonyms: "ditch, channel, furrow, excavation",
    notes: "",
  },
  {
    word: "enormous",
    definition: "Very large in size, quantity, or extent; huge",
    example: "The enormous whale breached the surface of the ocean.",
    synonyms: "huge, immense, vast, gigantic",
    notes: "",
  },
  {
    word: "scraped off",
    definition: "Removed by rubbing or scraping against a surface",
    example: "The old paint was scraped off before applying a new coat.",
    synonyms: "removed, peeled off, stripped away",
    notes: "Note: 原文為 'scrapted off' 應為 'scraped off'",
  },
  {
    word: "slab",
    definition: "A thick, flat piece of stone, concrete, or other hard material",
    example: "The patio was made from large concrete slabs.",
    synonyms: "block, plate, sheet, chunk",
    notes: "",
  },
  {
    word: "adjacent",
    definition: "Next to or adjoining something else; neighboring",
    example: "The hotel is adjacent to the beach.",
    synonyms: "neighboring, adjoining, next to, bordering",
    notes: "Note: 原文為 'adjacenttangled' 可能是兩個詞誤連",
  },
  {
    word: "mantle",
    definition: "The layer of the Earth between the crust and the core; a cloak or covering",
    example: "The Earth's mantle makes up about 84% of the planet's volume.",
    synonyms: "covering, cloak, layer",
    notes: "",
  },
  {
    word: "erupt",
    definition: "To burst forth or break out suddenly and violently",
    example: "The volcano could erupt at any moment.",
    synonyms: "explode, burst, blow up, discharge",
    notes: "",
  },
  {
    word: "divergent",
    definition: "Tending to be different or develop in different directions; diverging",
    example: "The two scientists had divergent opinions on the theory.",
    synonyms: "differing, varying, contrasting, conflicting",
    notes: "",
  },
  {
    word: "crust",
    definition: "The outermost solid shell of a planet; a hard outer layer",
    example: "The Earth's crust is divided into several tectonic plates.",
    synonyms: "outer layer, shell, surface, coating",
    notes: "",
  },
  {
    word: "continental",
    definition: "Relating to or characteristic of a continent",
    example: "Continental drift explains how continents move over time.",
    synonyms: "mainland, terrestrial",
    notes: "",
  },
  {
    word: "reservoirs",
    definition: "Large natural or artificial lakes used as sources of water supply",
    example: "The city's water comes from several reservoirs in the mountains.",
    synonyms: "lakes, pools, tanks, basins",
    notes: "",
  },
  {
    word: "crustal",
    definition: "Relating to the crust of the Earth",
    example: "Crustal movements can cause earthquakes.",
    synonyms: "",
    notes: "Note: 原文為 'custal' 應為 'crustal'",
  },
  {
    word: "impermeable",
    definition: "Not allowing fluid to pass through; waterproof",
    example: "The impermeable rock layer prevented water from seeping through.",
    synonyms: "waterproof, watertight, impervious, sealed",
    notes: "",
  },
  {
    word: "decaying",
    definition: "Rotting or decomposing; declining in quality, power, or vigor",
    example: "The decaying leaves enriched the soil.",
    synonyms: "rotting, decomposing, deteriorating, declining",
    notes: "",
  },
  {
    word: "proven",
    definition: "Demonstrated to be true or existing by evidence or argument",
    example: "The theory has been proven through extensive research.",
    synonyms: "established, verified, confirmed, demonstrated",
    notes: "",
  },
  {
    word: "hasten",
    definition: "To cause something to happen sooner or more quickly; to hurry",
    example: "We must hasten our preparations for the storm.",
    synonyms: "accelerate, speed up, quicken, expedite",
    notes: "",
  },
  {
    word: "asthmatics",
    definition: "People who suffer from asthma, a respiratory condition",
    example: "Asthmatics should always carry their inhalers.",
    synonyms: "",
    notes: "醫學術語：氣喘患者",
  },
  {
    word: "funeral",
    definition: "A ceremony honoring a dead person, typically involving burial or cremation",
    example: "The funeral was attended by hundreds of mourners.",
    synonyms: "burial, memorial service, obsequies",
    notes: "",
  },
  {
    word: "rheumatoid arthritis",
    definition: "A chronic progressive disease causing inflammation in the joints",
    example: "Rheumatoid arthritis can cause severe joint pain and stiffness.",
    synonyms: "",
    notes: "醫學術語：類風濕性關節炎",
  },
  {
    word: "obesity",
    definition: "The condition of being very overweight or having excessive body fat",
    example: "Obesity increases the risk of various health problems.",
    synonyms: "overweight, corpulence, fatness",
    notes: "",
  },
  {
    word: "merely",
    definition: "Just; only; nothing more than",
    example: "It was merely a suggestion, not an order.",
    synonyms: "simply, just, only, purely",
    notes: "",
  },
  {
    word: "disguise",
    definition: "To give a different appearance to conceal one's identity; a costume or outfit worn to hide identity",
    example: "She wore a disguise to avoid being recognized.",
    synonyms: "mask, camouflage, conceal, hide",
    notes: "",
  },
  {
    word: "specter",
    definition: "A ghost or phantom; something widely feared as a possible unpleasant occurrence",
    example: "The specter of war loomed over the region.",
    synonyms: "ghost, phantom, apparition, spirit",
    notes: "Note: 原文為 'spector' 應為 'specter'",
  },
  {
    word: "starvation",
    definition: "Suffering or death caused by lack of food",
    example: "The drought led to widespread starvation in the region.",
    synonyms: "hunger, famine, malnutrition",
    notes: "",
  },
  {
    word: "stalks",
    definition: "The main stems of plants; to pursue or approach stealthily",
    example: "The corn stalks grew tall in the summer heat.",
    synonyms: "stems, shoots, trunks",
    notes: "",
  },
  {
    word: "muscular sac",
    definition: "A pouch-like organ made of muscle tissue",
    example: "The heart is essentially a muscular sac that pumps blood.",
    synonyms: "",
    notes: "解剖學術語：肌肉囊",
  },
  {
    word: "endured",
    definition: "Suffered patiently; remained in existence; lasted",
    example: "She endured years of hardship before achieving success.",
    synonyms: "withstood, tolerated, survived, persevered",
    notes: "",
  },
  {
    word: "laboratory",
    definition: "A room or building equipped for scientific experiments, research, or teaching",
    example: "The scientists conducted experiments in the laboratory.",
    synonyms: "lab, research facility, testing center",
    notes: "",
  },
  {
    word: "swell",
    definition: "To become larger or rounder in size, typically as a result of accumulation of fluid",
    example: "Her ankle began to swell after the injury.",
    synonyms: "expand, enlarge, inflate, bulge",
    notes: "",
  },
  {
    word: "irresistible",
    definition: "Too attractive and tempting to be resisted; overwhelming",
    example: "The chocolate cake looked irresistible.",
    synonyms: "compelling, overwhelming, tempting, alluring",
    notes: "",
  },
  {
    word: "urge",
    definition: "A strong desire or impulse; to encourage or persuade strongly",
    example: "He felt a sudden urge to travel the world.",
    synonyms: "impulse, desire, compulsion, drive",
    notes: "",
  },
  {
    word: "appetite",
    definition: "A natural desire to satisfy a bodily need, especially for food",
    example: "The long hike gave us a healthy appetite.",
    synonyms: "hunger, craving, desire, taste",
    notes: "",
  },
  {
    word: "encompasses",
    definition: "Includes comprehensively; surrounds and has or holds within",
    example: "The course encompasses all aspects of digital marketing.",
    synonyms: "includes, comprises, contains, covers",
    notes: "",
  },
  {
    word: "rehabilitation",
    definition: "The action of restoring someone to health or normal life through training and therapy",
    example: "After the accident, she underwent months of rehabilitation.",
    synonyms: "recovery, restoration, therapy, treatment",
    notes: "",
  },
  {
    word: "cardiac",
    definition: "Relating to the heart",
    example: "He was admitted to the cardiac unit of the hospital.",
    synonyms: "heart-related, cardiovascular",
    notes: "",
  },
  {
    word: "practitioners",
    definition: "People actively engaged in an art, discipline, or profession",
    example: "Medical practitioners must keep up with the latest research.",
    synonyms: "professionals, specialists, experts",
    notes: "",
  },
  {
    word: "manufacturers",
    definition: "Companies or people that make goods in factories",
    example: "Car manufacturers are investing heavily in electric vehicles.",
    synonyms: "producers, makers, fabricators",
    notes: "Note: 原文為 'manufaturers' 應為 'manufacturers'",
  },
  {
    word: "friction",
    definition: "The resistance that one surface or object encounters when moving over another",
    example: "Oil reduces friction between moving parts.",
    synonyms: "resistance, rubbing, abrasion",
    notes: "",
  },
  {
    word: "impair",
    definition: "To weaken or damage something, especially a faculty or function",
    example: "Alcohol can impair your ability to drive safely.",
    synonyms: "damage, harm, weaken, diminish",
    notes: "",
  },
  {
    word: "carbohydrate",
    definition: "Any of a large group of organic compounds including sugars, starch, and cellulose",
    example: "Athletes often load up on carbohydrates before a race.",
    synonyms: "carbs, starches, sugars",
    notes: "",
  },
  {
    word: "fluid intake",
    definition: "The amount of liquid consumed",
    example: "Doctors recommend increasing fluid intake when you have a fever.",
    synonyms: "liquid consumption, hydration",
    notes: "",
  },
  {
    word: "amphetamines",
    definition: "Synthetic stimulant drugs used to treat certain medical conditions",
    example: "Amphetamines are sometimes prescribed for ADHD.",
    synonyms: "stimulants, uppers",
    notes: "藥物名稱：安非他命",
  },
  {
    word: "anabolic",
    definition: "Relating to or promoting anabolism, the synthesis of complex molecules in living organisms",
    example: "Anabolic processes build up organs and tissues.",
    synonyms: "constructive, building",
    notes: "",
  },
  {
    word: "steroids",
    definition: "Organic compounds including many hormones, alkaloids, and vitamins",
    example: "Some athletes illegally use steroids to enhance performance.",
    synonyms: "",
    notes: "類固醇",
  },
  {
    word: "paddle",
    definition: "A short pole with a broad blade at one or both ends, used to propel a boat",
    example: "She used the paddle to steer the canoe down the river.",
    synonyms: "oar, blade",
    notes: "",
  },
  {
    word: "barrel",
    definition: "A cylindrical container bulging out in the middle; the tube of a gun",
    example: "The wine was aged in oak barrels.",
    synonyms: "cask, keg, drum, cylinder",
    notes: "",
  },
  {
    word: "converted back and forth",
    definition: "Changed repeatedly from one form or function to another and vice versa",
    example: "The energy is converted back and forth between kinetic and potential forms.",
    synonyms: "transformed alternately, switched repeatedly",
    notes: "",
  },
  {
    word: "conservation",
    definition: "The action of conserving something; preservation or restoration of the natural environment",
    example: "Wildlife conservation is crucial for protecting endangered species.",
    synonyms: "preservation, protection, maintenance",
    notes: "",
  },
  {
    word: "cornerstone",
    definition: "An important quality or feature on which a particular thing depends; a foundation",
    example: "Trust is the cornerstone of any successful relationship.",
    synonyms: "foundation, basis, keystone, fundamental",
    notes: "",
  },
  {
    word: "autos",
    definition: "Automobiles; cars",
    example: "The factory produces thousands of autos each year.",
    synonyms: "cars, vehicles, automobiles",
    notes: "",
  },
  {
    word: "offset",
    definition: "To counterbalance or compensate for something",
    example: "The gains in the stock market offset the losses in bonds.",
    synonyms: "counterbalance, compensate, neutralize",
    notes: "",
  },
  {
    word: "bequeathed",
    definition: "Left or gave (personal property) to someone in a will",
    example: "She bequeathed her entire art collection to the museum.",
    synonyms: "left, willed, handed down, inherited",
    notes: "",
  },
  {
    word: "consolidation",
    definition: "The action or process of combining things into a single more effective whole",
    example: "The consolidation of the two companies created a market leader.",
    synonyms: "merger, unification, combination, integration",
    notes: "",
  },
  {
    word: "equation",
    definition: "A mathematical statement that two expressions are equal; a situation or problem with several factors",
    example: "Solving this equation requires advanced algebra skills.",
    synonyms: "formula, expression, calculation",
    notes: "",
  },
  {
    word: "geometry",
    definition:
      "The branch of mathematics concerned with properties and relations of points, lines, surfaces, and solids",
    example: "Students learn basic geometry in middle school.",
    synonyms: "",
    notes: "幾何學",
  },
  {
    word: "rigid",
    definition: "Unable to bend or be forced out of shape; not flexible",
    example: "The rigid steel frame provided excellent support.",
    synonyms: "stiff, inflexible, firm, unyielding",
    notes: "",
  },
  {
    word: "elastic",
    definition: "Able to resume normal shape after being stretched or compressed; flexible",
    example: "The elastic band snapped back into place.",
    synonyms: "stretchy, flexible, pliable, springy",
    notes: "",
  },
  {
    word: "discourse",
    definition: "Written or spoken communication or debate; a formal discussion of a topic",
    example: "The professor engaged in academic discourse about climate change.",
    synonyms: "discussion, conversation, dialogue, debate",
    notes: "",
  },
  {
    word: "disciplinary",
    definition: "Relating to discipline or a particular field of study; concerning punishment",
    example: "The student faced disciplinary action for cheating.",
    synonyms: "punitive, corrective, regulatory",
    notes: "",
  },
];
module.exports = CARDS;