/* cards.cjs
   ──────────
   將單字清單宣告成常數，並以 CommonJS 匿名匯出。
   其他檔案只要 `require('./cards.cjs')` 就能取得整個陣列。 */
   const CARDS = [
     {
       word: "grainy",
       definition:
         "If an image, film, or photograph is grainy, it is not smooth or clear because the small particles that make it up are visible.",
       example: "The low-light photo looked grainy because I set the ISO too high.",
       synonyms: "rocky, gritty",
       notes: "Root: grain (wheat is a grain that is grown in Kansas)",
     },
     {
       word: "anecdotal",
       definition: "Based on personal accounts rather than on reliable research or statistics.",
       example: "Anecdotal evidence suggested that the new app was helping students focus better.",
       synonyms: "unreliable, informal",
       notes: "",
     },
     {
       word: "translucent",
       definition: "Almost transparent; allowing some light to pass through in a soft, diffused way.",
       example: "We installed translucent curtains that let in a gentle morning glow.",
       synonyms: "semi-transparent",
       notes: "Contrast: transparent (lets all light through) vs. opaque (lets no light through).",
     },
     {
       word: "opaque",
       definition: "Not able to be seen through; not letting light pass through.",
       example: "The bathroom window is made of opaque glass for privacy.",
       synonyms: "non-transparent, cloudy, impenetrable",
       notes: "",
     },
     {
       word: "stationary",
       definition: "Not moving; staying in one place or position.",
       example: "Keep the tripod stationary while you take the long-exposure shot.",
       synonyms: "immobile, static",
       notes: "⚠️ Do not confuse with **stationery** (writing materials).",
     },
     {
       word: "abstract",
       definition: "Existing as an idea, feeling, or quality rather than as a tangible object.",
       example: "Justice is an abstract concept that can be hard to define.",
       synonyms: "conceptual, theoretical",
       notes: "",
     },
     {
       word: "conventional",
       definition: "Based on or in accordance with what is generally done or believed; traditional.",
       example: "He chose a conventional black suit for the interview.",
       synonyms: "traditional, customary, regular",
       notes: "Root: convent (修道院).",
     },
     {
       word: "venture",
       definition:
         "1) A new activity or business that involves risk or uncertainty. 2) To go somewhere or do something risky or daring.",
       example: "Their latest venture involves setting up a solar-energy start-up in Africa.",
       synonyms: "undertaking, enterprise",
       notes: "Venture = goal-oriented; Adventure = no specific goal.",
     },
     {
       word: "inception",
       definition: "The beginning or start of something, especially an organization or activity.",
       example: "The charity has grown significantly since its inception in 2015.",
       synonyms: "start, outset, origin",
       notes: "",
     },
     {
       word: "immersive",
       definition: "Seeming to surround a person so that they feel completely involved.",
       example: "The VR headset delivers an incredibly immersive gaming experience.",
       synonyms: "engaging, enveloping",
       notes: "",
     },
     {
       word: "ambition",
       definition: "A strong desire to achieve something.",
       example: "Her ambition is to become a leading neuroscientist.",
       synonyms: "aspiration, dream, goal",
       notes: "",
     },
     {
       word: "surveillance",
       definition: "Close observation, especially of a suspected person or place.",
       example: "The warehouse has been under constant surveillance since the robbery.",
       synonyms: "monitoring, observation",
       notes: "Verb form: <b>surveil</b>; Warrants often allow agents to surveil electronic communications.",
     },
     {
       word: "ponder",
       definition: "To think about something carefully for a considerable time.",
       example: "He paused to ponder the implications of the new proposal.",
       synonyms: "contemplate, consider, deliberate",
       notes: "",
     },
     {
       word: "acne",
       definition: "A common skin condition that causes spots or pimples, especially on the face.",
       example: "Many teenagers struggle with acne during puberty.",
       synonyms: "pimples, spots",
       notes: "",
     },
     {
       word: "puberty",
       definition:
         "The physical stage of development during which a child's body matures into an adult body capable of reproduction.",
       example: "Her voice deepened when she reached puberty.",
       synonyms: "adolescence",
       notes: "",
     },
     {
       word: "emotionally vulnerable",
       definition: "Easily hurt or affected emotionally; sensitive to criticism or rejection.",
       example: "After the breakup he felt emotionally vulnerable and avoided social events.",
       synonyms: "sensitive, fragile",
       notes: "",
     },
     {
       word: "trivialise",
       definition: "To make something seem less important or serious than it really is.",
       example: "I don’t want to trivialise the issue, but there are bigger problems to solve.",
       synonyms: "downplay, minimise",
       notes: "",
     },
     {
       word: "over the counter",
       definition: "Describes medicines that can be bought without a prescription.",
       example: "You can buy many pain relievers over the counter.",
       synonyms: "non-prescription",
       notes: "See also: prescription drugs. 相關維基百科連結已提供。",
     },
     {
       word: "obsessed",
       definition: "Unable to stop thinking about something; too interested in or worried about it.",
       example: "He is completely obsessed with vintage cars.",
       synonyms: "fixated, preoccupied",
       notes: "",
     },
     {
       word: "pursuit",
       definition:
         "1) The act of trying to achieve something over a long period. 2) The act of following to catch. 3) An activity done regularly for enjoyment.",
       example: "She moved abroad in pursuit of a career in international law.",
       synonyms: "quest, chase, hobby",
       notes: "",
     },
     {
       word: "testosterone",
       definition: "A male hormone that stimulates growth of male secondary sexual characteristics.",
       example: "Testosterone levels typically rise sharply during adolescence.",
       synonyms: "androgen, male hormone",
       notes: "",
     },
     {
       word: "pore",
       definition: "A very small opening in the skin through which sweat can pass.",
       example: "Sweat escapes through the pores and cools the body.",
       synonyms: "opening, hole",
       notes: "",
     },
     {
       word: "dermatologist",
       definition: "A doctor who specializes in treating skin disorders.",
       example: "The dermatologist prescribed a cream for my eczema.",
       synonyms: "skin doctor",
       notes: "",
     },
     {
       word: "bane",
       definition: "A cause of great distress, annoyance, or ruin.",
       example: "Mosquitoes are the bane of my summer evenings.",
       synonyms: "curse, scourge, torment",
       notes: 'Common phrase: "bane of my life".',
     },
     {
       word: "idiom",
       definition:
         "A phrase whose meaning is different from the meanings of the individual words; also, a characteristic style of expression.",
       example: '"Break the ice" is an English idiom meaning to make people feel more comfortable.',
       synonyms: "expression, phrase",
       notes: "",
     },
     {
       word: "testament",
       definition: "Proof or evidence of something; also, a person's will.",
       example: "The award is a testament to her years of dedication.",
       synonyms: "proof, evidence, will",
       notes: "",
     },
     {
       word: "ophthalmology",
       definition:
         "The branch of medicine concerned with the study and treatment of disorders and diseases of the eye.",
       example: "He is completing his residency in ophthalmology.",
       synonyms: "eye medicine",
       notes: "",
     },
     {
       word: "simultaneously",
       definition: "At the same time.",
       example: "The concert was broadcast simultaneously on radio and television.",
       synonyms: "concurrently, at once",
       notes: "",
     },
     {
       word: "revelation",
       definition: "The act of making something known that was secret; a surprising fact that is made known.",
       example: "The memoir was full of startling revelations about her past.",
       synonyms: "disclosure, unveiling",
       notes: "",
     },
     {
       word: "revel",
       definition: "To enjoy oneself in a lively and noisy way, especially with drinking and dancing.",
       example: "Fans reveled in their team’s unexpected victory.",
       synonyms: "celebrate, carouse, rejoice",
       notes: "",
     },
     {
       word: "speculation",
       definition: "Ideas or guesses about something that is not known for certain.",
       example: "There has been widespread speculation about the company's next product launch.",
       synonyms: "conjecture, guesswork",
       notes: "",
     },
     {
       word: "sensational",
       definition: "Causing great public interest and excitement; extremely good or impressive.",
       example: "The tabloid is known for its sensational headlines.",
       synonyms: "dramatic, shocking, spectacular",
       notes: "",
     },
     {
       word: "massive",
       definition: "Exceptionally large, heavy, or extensive.",
       example: "A massive earthquake struck the region last night.",
       synonyms: "huge, enormous, colossal",
       notes: "",
     },
     {
       word: "cohost",
       definition: "To jointly present or host a program, event, or show.",
       example: "She cohosts a popular tech podcast every week.",
       synonyms: "joint host",
       notes: "",
     },
     {
       word: "recalibrate",
       definition:
         "To adjust or correct the settings of a device, instrument, or process; to reassess and make small changes.",
       example: "After replacing the sensor, engineers had to recalibrate the entire system.",
       synonyms: "readjust, fine-tune",
       notes: "",
     },
     {
       word: "cellist",
       definition: "A musician who plays the cello.",
       example: "The cellist performed a moving solo during the concert.",
       synonyms: "cello player",
       notes: "Instrument: cello 大提琴",
     },
     {
       word: "transcend",
       definition: "To rise above or go beyond the limits of something.",
       example: "Great art can transcend cultural boundaries.",
       synonyms: "surpass, exceed, rise above",
       notes: "",
     },
     {
       word: "erosion",
       definition: "The gradual wearing away of soil, rock, or land by natural forces such as wind or water.",
       example: "Coastal erosion has reduced the width of the beach over the past decade.",
       synonyms: "wearing away, abrasion",
       notes: "Refers especially to natural phenomena.",
     },
   ];

module.exports = CARDS; // 匯出陣列
