const CARDS = [
  {
    word: "aberration",
    definition: "A departure from what is normal, usual, or expected, typically an unwelcome one",
    example: "The company's poor performance this quarter was an aberration from its usual success.",
    synonyms: "anomaly, deviation, irregularity, abnormality",
    notes: "n. 偏差、異常",
  },
  {
    word: "acrimony",
    definition: "Bitterness or ill feeling in speech or manner",
    example: "The debate was filled with acrimony, with both sides exchanging harsh words.",
    synonyms: "bitterness, animosity, hostility, resentment",
    notes: "n. 尖刻、辛辣",
  },
  {
    word: "amalgam",
    definition: "A mixture or blend of different elements",
    example: "The new policy is an amalgam of traditional and progressive approaches.",
    synonyms: "mixture, blend, combination, fusion",
    notes: "n. 混合物、合金",
  },
  {
    word: "ambiguous",
    definition: "Having more than one possible meaning; open to more than one interpretation",
    example: "The contract's ambiguous wording led to disputes between the parties.",
    synonyms: "unclear, vague, equivocal, indefinite",
    notes: "adj. 模稜兩可的、含糊不清的",
  },
  {
    word: "ambivalent",
    definition: "Having mixed feelings or contradictory ideas about something or someone",
    example: "She felt ambivalent about accepting the job offer in another city.",
    synonyms: "conflicted, uncertain, undecided, torn",
    notes: "adj. 矛盾的、搖擺不定的",
  },
  {
    word: "amenable",
    definition: "Open and responsive to suggestion; easily persuaded or controlled",
    example: "The manager was amenable to our proposal for flexible working hours.",
    synonyms: "agreeable, compliant, accommodating, receptive",
    notes: "adj. 順從的、願意接受的",
  },
  {
    word: "amorphous",
    definition: "Without a clearly defined shape or form; lacking structure",
    example: "The committee's goals remained amorphous and difficult to measure.",
    synonyms: "shapeless, formless, unstructured, nebulous",
    notes: "adj. 無定形的、模糊的",
  },
  {
    word: "anomalous",
    definition: "Deviating from what is standard, normal, or expected",
    example: "The scientists discovered anomalous readings in their data.",
    synonyms: "abnormal, irregular, unusual, atypical",
    notes: "adj. 異常的、不規則的",
  },
  {
    word: "artful",
    definition: "Clever or skillful, especially in a crafty or cunning way",
    example: "The lawyer's artful questioning revealed inconsistencies in the witness's testimony.",
    synonyms: "cunning, crafty, clever, skillful",
    notes: "adj. 巧妙的、狡猾的",
  },
  {
    word: "auspicious",
    definition: "Conducive to success; favorable; giving signs of future success",
    example: "The sunny weather was an auspicious start to their wedding day.",
    synonyms: "favorable, promising, propitious, fortunate",
    notes: "adj. 吉利的、有前途的",
  },
  {
    word: "belie",
    definition: "To fail to give a true impression of something; to contradict",
    example: "Her calm demeanor belied the anxiety she felt inside.",
    synonyms: "contradict, misrepresent, disguise, conceal",
    notes: "v. 掩飾、與...矛盾",
  },
  {
    word: "betray",
    definition: "To reveal unintentionally; to be disloyal to",
    example: "His trembling hands betrayed his nervousness during the presentation.",
    synonyms: "reveal, expose, disclose; deceive",
    notes: "v. 背叛、洩露",
  },
  {
    word: "calumny",
    definition: "The making of false and defamatory statements about someone",
    example: "The politician faced calumny from opponents trying to damage her reputation.",
    synonyms: "slander, defamation, libel, vilification",
    notes: "n. 誹謗、中傷",
  },
  {
    word: "castigate",
    definition: "To reprimand someone severely",
    example: "The coach castigated the team for their poor performance.",
    synonyms: "criticize, reprimand, rebuke, chastise",
    notes: "v. 嚴厲批評、懲戒",
  },
  {
    word: "censure",
    definition: "To express severe disapproval of someone or something",
    example: "The committee voted to censure the member for unethical behavior.",
    synonyms: "condemn, criticize, denounce, reproach",
    notes: "v./n. 譴責、指責",
  },
  {
    word: "chastise",
    definition: "To rebuke or reprimand severely",
    example: "The teacher chastised the student for cheating on the exam.",
    synonyms: "scold, reprimand, rebuke, admonish",
    notes: "v. 懲戒、責罵",
  },
  {
    word: "commensurate",
    definition: "Corresponding in size, degree, or extent; proportionate",
    example: "Her salary is commensurate with her experience and qualifications.",
    synonyms: "proportionate, equivalent, corresponding, comparable",
    notes: "adj. 相稱的、成比例的",
  },
  {
    word: "demur",
    definition: "To raise objections or show reluctance",
    example: "When asked to work overtime again, she demurred politely.",
    synonyms: "object, protest, hesitate, resist",
    notes: "v. 表示異議、反對",
  },
  {
    word: "disinterested",
    definition: "Not influenced by personal feelings or opinions; impartial",
    example: "A judge must remain disinterested when presiding over a case.",
    synonyms: "impartial, unbiased, neutral, objective",
    notes: "adj. 公正的、無私的（注意：不是「不感興趣」）",
  },
  {
    word: "egregious",
    definition: "Outstandingly bad; shocking",
    example: "The company's egregious safety violations led to heavy fines.",
    synonyms: "flagrant, glaring, outrageous, shocking",
    notes: "adj. 極其惡劣的、驚人的",
  },
  {
    word: "enervate",
    definition: "To cause someone to feel drained of energy or vitality; to weaken",
    example: "The hot, humid weather enervated the hikers.",
    synonyms: "exhaust, weaken, debilitate, drain",
    notes: "v. 使衰弱、使失去活力",
  },
  {
    word: "equivocal",
    definition: "Open to more than one interpretation; ambiguous",
    example: "The politician gave an equivocal answer to avoid taking a clear stance.",
    synonyms: "ambiguous, vague, unclear, indefinite",
    notes: "adj. 模稜兩可的、含糊的",
  },
  {
    word: "extant",
    definition: "Still in existence; surviving",
    example: "Only three copies of the manuscript are extant today.",
    synonyms: "existing, surviving, remaining, present",
    notes: "adj. 現存的、尚存的",
  },
  {
    word: "frugal",
    definition: "Sparing or economical with regard to money or food",
    example: "Her frugal lifestyle allowed her to save most of her income.",
    synonyms: "thrifty, economical, sparing, prudent",
    notes: "adj. 節儉的、儉樸的",
  },
  {
    word: "galvanize",
    definition: "To shock or excite someone into taking action",
    example: "The environmental disaster galvanized the community into action.",
    synonyms: "stimulate, motivate, energize, inspire",
    notes: "v. 激勵、刺激",
  },
  {
    word: "gregarious",
    definition: "Fond of company; sociable",
    example: "His gregarious personality made him popular at social gatherings.",
    synonyms: "sociable, outgoing, friendly, convivial",
    notes: "adj. 合群的、愛社交的",
  },
  {
    word: "harangue",
    definition: "A lengthy and aggressive speech",
    example: "The coach delivered a harangue about the team's lack of commitment.",
    synonyms: "tirade, lecture, diatribe, rant",
    notes: "n./v. 長篇大論、激烈演說",
  },
  {
    word: "iconoclast",
    definition: "A person who attacks or criticizes cherished beliefs or institutions",
    example: "The artist was an iconoclast who challenged traditional art forms.",
    synonyms: "rebel, nonconformist, maverick, dissenter",
    notes: "n. 打破傳統的人、反傳統者",
  },
  {
    word: "impertinent",
    definition: "Not showing proper respect; rude",
    example: "The student's impertinent remarks earned him detention.",
    synonyms: "rude, insolent, impudent, disrespectful",
    notes: "adj. 無禮的、不敬的",
  },
  {
    word: "ingenuous",
    definition: "Innocent and unsuspecting; showing childlike simplicity",
    example: "Her ingenuous smile revealed her genuine surprise at the party.",
    synonyms: "naive, innocent, artless, guileless",
    notes: "adj. 天真的、坦率的",
  },
  {
    word: "innocuous",
    definition: "Not harmful or offensive",
    example: "What seemed like an innocuous comment actually offended many people.",
    synonyms: "harmless, safe, inoffensive, benign",
    notes: "adj. 無害的、無毒的",
  },
  {
    word: "intimate",
    definition: "To make known subtly or indirectly; to hint",
    example: "She intimate that she might be leaving the company soon.",
    synonyms: "suggest, hint, imply, indicate",
    notes: "v. 暗示、透露（動詞用法）",
  },
  {
    word: "involved",
    definition: "Complex or intricate; difficult to understand",
    example: "The instructions were so involved that many people couldn't follow them.",
    synonyms: "complex, complicated, intricate, elaborate",
    notes: "adj. 複雜的、難懂的",
  },
  {
    word: "laconic",
    definition: "Using very few words; concise",
    example: "His laconic reply of 'yes' ended the lengthy discussion.",
    synonyms: "brief, concise, terse, succinct",
    notes: "adj. 簡潔的、言簡意賅的",
  },
  {
    word: "maintain",
    definition: "To state or assert as true; to uphold",
    example: "The defendant continues to maintain his innocence.",
    synonyms: "assert, claim, declare, insist",
    notes: "v. 堅持、主張（此處非「維持」之意）",
  },
  {
    word: "mercurial",
    definition: "Subject to sudden or unpredictable changes of mood or mind",
    example: "Her mercurial temperament made it difficult to work with her.",
    synonyms: "volatile, unpredictable, changeable, capricious",
    notes: "adj. 善變的、反覆無常的",
  },
  {
    word: "parochial",
    definition: "Having a limited or narrow outlook or scope",
    example: "His parochial views prevented him from seeing the bigger picture.",
    synonyms: "narrow-minded, provincial, insular, limited",
    notes: "adj. 狹隘的、地方性的",
  },
  {
    word: "parsimonious",
    definition: "Extremely frugal; unwilling to spend money",
    example: "The parsimonious millionaire lived in a modest apartment.",
    synonyms: "stingy, miserly, frugal, penny-pinching",
    notes: "adj. 吝嗇的、過度節儉的",
  },
  {
    word: "prevaricate",
    definition: "To speak or act in an evasive way; to avoid telling the truth",
    example: "When asked about the missing funds, he began to prevaricate.",
    synonyms: "equivocate, evade, hedge, dodge",
    notes: "v. 支吾其詞、搪塞",
  },
  {
    word: "prodigal",
    definition: "Spending money or resources freely and recklessly; wastefully extravagant",
    example: "His prodigal spending habits led to bankruptcy.",
    synonyms: "wasteful, extravagant, spendthrift, profligate",
    notes: "adj. 揮霍的、浪費的",
  },
  {
    word: "profligate",
    definition: "Recklessly extravagant or wasteful in the use of resources",
    example: "The profligate use of water during the drought was criticized.",
    synonyms: "wasteful, extravagant, spendthrift, dissolute",
    notes: "adj. 揮霍無度的、放蕩的",
  },
  {
    word: "qualify",
    definition: "To make less absolute; to add reservations to",
    example: "She qualified her statement by adding several exceptions.",
    synonyms: "modify, limit, restrict, temper",
    notes: "v. 限定、修飾（使不那麼絕對）",
  },
  {
    word: "restive",
    definition: "Unable to keep still or silent; restless",
    example: "The audience grew restive during the long, boring speech.",
    synonyms: "restless, fidgety, uneasy, impatient",
    notes: "adj. 焦躁不安的、難以控制的",
  },
  {
    word: "undermine",
    definition: "To erode the base or foundation of; to weaken or damage",
    example: "Constant criticism can undermine a person's confidence.",
    synonyms: "weaken, sabotage, subvert, damage",
    notes: "v. 削弱、破壞",
  },
  {
    word: "upbraid",
    definition: "To find fault with someone; to scold",
    example: "She upbraided him for forgetting their anniversary.",
    synonyms: "scold, reprimand, reproach, rebuke",
    notes: "v. 責備、訓斥",
  },
  {
    word: "venality",
    definition: "The condition of being susceptible to bribery or corruption",
    example: "The venality of the officials led to widespread distrust in government.",
    synonyms: "corruption, corruptibility, dishonesty, bribery",
    notes: "n. 貪污、唯利是圖",
  },
  {
    word: "venerate",
    definition: "To regard with great respect; to revere",
    example: "The students venerate their wise and compassionate teacher.",
    synonyms: "revere, respect, honor, admire",
    notes: "v. 崇敬、尊敬",
  },
  {
    word: "veracious",
    definition: "Speaking or representing the truth; truthful and accurate",
    example: "The journalist was known for her veracious reporting.",
    synonyms: "truthful, honest, accurate, sincere",
    notes: "adj. 誠實的、真實的",
  },
  {
    word: "vindicate",
    definition: "To clear someone of blame or suspicion; to justify",
    example: "The new evidence vindicated the suspect who had been wrongly accused.",
    synonyms: "exonerate, justify, absolve, clear",
    notes: "v. 證明...正確、為...平反",
  },
  {
    word: "wanting",
    definition: "Lacking or deficient in something; not having enough",
    example: "The proposal was found wanting in several key areas.",
    synonyms: "lacking, deficient, inadequate, insufficient",
    notes: "adj. 缺乏的、不足的",
  },
];

module.exports = CARDS;
